version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "gh-pages"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
